## Imports:

In [1]:
import scipy.io
import os
import pandas
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.pylab as plt_lab
import matplotlib.gridspec as gridspec
import obspy
import pandas as pd

RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd

In [2]:
import warnings
warnings.filterwarnings('ignore')

## Load data:
We are going to use this data to plot spectograms of SCG signals.

In [3]:
dir_path = "/Users/ecem/Documents/GitHub/seismocardiogram/data/diseased-dataset/Raw_Recordings"
csv_path = "/Users/ecem/Desktop/csv of scgs"

In [5]:
df = pd.read_csv((csv_path + "/all-diseases-as-binary.csv"))

In [9]:
list_ = [44,
55,
55,
43,
37,
37,
49,
49,
49,
49,
58,
43,
43,
49,
50,
47,
53,
44,
44,
55,
40,
42,
43,
48,
46,
41,
39,
37,
38,
57,
41,
42,
43,
41,
45,
41,
43,
46,
43,
33,
29,
32,
27,
26,
26,
27,
27,
29,
29,
30,
27,
27,
43,
56,
26,
26,
26,
26,
25,
26]

In [10]:
len(list_)

60

In [11]:
sum(list_)

2392

In [15]:
en = enumerate(list_)
en

In [16]:
for i, j in en:
    print(i,"****", j)

0 **** 44
1 **** 55
2 **** 55
3 **** 43
4 **** 37
5 **** 37
6 **** 49
7 **** 49
8 **** 49
9 **** 49
10 **** 58
11 **** 43
12 **** 43
13 **** 49
14 **** 50
15 **** 47
16 **** 53
17 **** 44
18 **** 44
19 **** 55
20 **** 40
21 **** 42
22 **** 43
23 **** 48
24 **** 46
25 **** 41
26 **** 39
27 **** 37
28 **** 38
29 **** 57
30 **** 41
31 **** 42
32 **** 43
33 **** 41
34 **** 45
35 **** 41
36 **** 43
37 **** 46
38 **** 43
39 **** 33
40 **** 29
41 **** 32
42 **** 27
43 **** 26
44 **** 26
45 **** 27
46 **** 27
47 **** 29
48 **** 29
49 **** 30
50 **** 27
51 **** 27
52 **** 43
53 **** 56
54 **** 26
55 **** 26
56 **** 26
57 **** 26
58 **** 25
59 **** 26

In [12]:
array = df.to_csv()

In [27]:
array_ = array[0]

In [30]:
for i, j in en: #0,43
    dummy = array[i]
    for k in range(j): #43
        array_ = np.concatenate((array_, dummy), axis = 0)

In [31]:
array_

','

In [32]:
array = df.to_numpy()

In [33]:
array

array([[0., 1., 0., 0.],
       [1., 1., 1., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 1., 1., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 1., 1.],
       [0., 1., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 1.],
       [0., 1., 0., 0.],
       [1., 1., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]])

In [34]:
array_ = array[0]

In [35]:
for i in range(60):
    a  = array[i]
    for j in list_:
        array_ = np.vstack([array_, a])
        
    list_.pop(0)
    print(len(list_))

59
58
57
56
55
54
53
52
51
50
49
48
47
46
45
44
43
42
41
40
39
38
37
36
35
34
33
32
31
30
29
28
27
26
25
24
23
22
21
20
19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0

In [36]:
array_.shape

(1831, 4)

In [37]:
for i, j in en: #0,43
    for k in range(j): #43
        df_dummy = df.iloc[i,:]
        df_ = pd.concat([df_, df_dummy])

In [22]:
for k in range(43): #43
        array_ = np.vstack([array_, a])

NameError: name 'array_' is not defined

In [39]:
array_

array([[0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       ...,
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]])

In [40]:
all_diseases.loc[all_diseases["Moderate or greater MS"] == 1, "Moderate or greater MS"] = "MS"
#all_diseases

In [41]:
all_diseases.loc[all_diseases["Moderate or greater MR"] == 1, "Moderate or greater MR"] = "MR"
all_diseases.loc[all_diseases["Moderate or greater AS"] == 1, "Moderate or greater AS"] = "AS"
all_diseases.loc[all_diseases["Moderate or greater AR"] == 1, "Moderate or greater AR"] = "AR"
all_diseases

,Moderate or greater MS,Moderate or greater MR,Moderate or greater AR,Moderate or greater AS
0,0.0,MR,0.0,0.0
1,MS,MR,AR,AS
2,0.0,MR,0.0,0.0
4,0.0,0.0,AR,AS
5,0.0,0.0,0.0,0.0
6,0.0,0.0,0.0,0.0
7,0.0,0.0,0.0,0.0
8,MS,0.0,0.0,0.0
12,0.0,MR,0.0,0.0
14,MS,MR,AR,AS
17,0.0,0.0,AR,0.0
19,0.0,MR,0.0,0.0
21,0.0,0.0,AR,0.0
25,0.0,MR,AR,0.0
26,0.0,0.0,AR,0.0
27,0.0,MR,0.0,0.0
28,MS,0.0,0.0,0.0
29,0.0,0.0,0.0,0.0
31,0.0,MR,0.0,0.0
32,0.0,MR,0.0,0.0
36,0.0,MR,AR,0.0
37,0.0,MR,0.0,0.0
38,0.0,MR,AR,0.0
39,0.0,0.0,AR,0.0
40,0.0,MR,AR,AS
43,0.0,MR,AR,0.0
44,0.0,0.0,0.0,AS
45,0.0,MR,0.0,0.0
46,MS,MR,0.0,0.0
49,MS,MR,0.0,AS
50,0.0,MR,0.0,0.0
52,MS,MR,AR,0.0
54,0.0,MR,0.0,0.0
58,0.0,MR,AR,0.0
60,0.0,MR,0.0,0.0
62,MS,0.0,0.0,0.0
64,0.0,MR,AR,0.0
65,0.0,MR,0.0,0.0
68,0.0,0.0,AR,0.0
71,0.0,0.0,0.0,AS
73,0.0,0.0,0.0,AS
76,0.0,0.0,0.0,AS
78,0.0,0.0,0.0,AS
79,MS,0.0,0.0,AS
80,0.0,0.0,0.0,AS
81,MS,0.0,0.0,AS
82,0.0,MR,0.0,AS
83,MS,0.0,0.0,AS
84,0.0,0.0,0.0,AS
85,0.0,0.0,0.0,AS
87,0.0,0.0,0.0,AS
88,0.0,0.0,0.0,AS
89,0.0,MR,0.0,AS
92,0.0,0.0,0.0,AS
94,0.0,MR,0.0,AS
95,0.0,0.0,0.0,AS
96,0.0,0.0,0.0,AS
97,0.0,0.0,0.0,AS
98,0.0,0.0,0.0,AS
99,0.0,0.0,0.0,AS

In [42]:
#all_diseases.to_csv("/Users/ecem/Desktop/csv of scgs")

In [43]:
#all_diseases.to_csv(csv_path  + "/all-diseases-as-string.csv")